### ISSUE TITLE
Nested tasks ignore serial project type

### ISSUE THREAD

**Issue by nikdoof** [nikdoof/NextAction#2]
- Task 1
- Task 2
  - Task 2.1

Task 1 and Task 2.1 are tagged as next actions in a serial type project, Task 1 should be the only one tagged. In the following situation
- Task 1
  - Task 1.1
- Task 2

Task 1.1 should be only one tagged.

**Comment by ildr3him** [comment]
I think I have the same problem.

http://i.imgur.com/mYLQQbG.png

Running developer branch on mac system with the "noob" method listed in another issue thread here
