### ISSUE TITLE
How To Install & Run On Mac For Newbies

### ISSUE THREAD

**Issue by tailoredfilter** [nikdoof/NextAction#5]
I would love to be able to use your NextAction script since I'm a hard core Todoist user. However, I know nothing about python or code. Could you provide step by step instructions for a someone who doesn't know anything about this stuff? 

I downloaded Python, but don't know what to do. 

Thanks in advance and thanks for making this. I hope I can put it to use.

**Comment by patertmg** [comment]
Same here. Would be great to have the NextAction function in Todoist, since this is a key feature of GTD, right?

**Comment by nikdoof** [comment]
Yes, documentation for installation is a seriously lacking feature at the moment. Essentially:

* Python comes pre-installed with OSX, no further packages are needed
* Download and extract the [zip](https://github.com/nikdoof/NextAction/archive/development.zip)
* From the extracted directory run `sudo python ./setup.py install`
* The `nextaction` command should now be available to you to use as per the normal documentation.

This is by no means the best way to install this, but its a workable solution. Ideally this should be installed on a system that is available all the time to keep your Todoist up to date.
