### ISSUE TITLE
Getting an "unexpected keyword argument 'resource_types'" after install

### ISSUE THREAD

**Issue by benster** [nikdoof/NextAction#6]
After doing a python setup.py install and trying to run this (with a valid API token), I get the following:

Traceback (most recent call last):
  File "C:\Python27\Scripts\nextaction-script.py", line 9, in <module>
    load_entry_point('NextAction==0.3', 'console_scripts', 'nextaction')()
  File "build\bdist.win32\egg\nextaction.py", line 69, in main
TypeError: sync() got an unexpected keyword argument 'resource_types'

**Comment by iamtechman** [comment]
I have the same issue.

**Comment by nikdoof** [comment]
Looks like the python-todoist library updated and [depreciated calling sync with resource types](https://github.com/Doist/todoist-python/commit/2a5fb5cb07f81f64e898d857792d36704c803ae9). Should be a relatively small fix, but for the meantime you could install python-todoist version 0.2.26 with:

```pip install python-todoist==0.2.26```

As the latest version of the lib seems to have moved API versions as well (to v7) I need to do a lot more checking before competing this fix. For the moment i'll update the requirements.

**Comment by benster** [comment]
Yes, I saw that - thanks for confirming.  For now I removed the resource_type args from the 2(?) calls in the script and it works fine.  I increased the delay between calls due to the increased data that's returned - disappointed to see that they deprecated that functionality :(  I might install the earlier version of the lib and wait for an update of this script to see where we are at that point.

**Comment by iamtechman** [comment]
I'm getting this when trying to load python 0.2.26

  Could not find a version that satisfies the requirement python-todoist==0.2.26 (from versions: )
No matching distribution found for python-todoist==0.2.26

**Comment by iamtechman** [comment]
Also, if benster could explain how to remove the resource_type args without causing syntax or indent errors.

**Comment by benster** [comment]
I got the same error when trying to downgrade the library so I left it as-is for now.  To remove the resource_type args, just edit the script and change the 2 calls to sync() by removing the resource_types argument from each call - search the file for resource_types and remove those args from each call.

**Comment by iamtechman** [comment]
Thank you benster. I've got it working, but it doesn't seem to work the way it should.  The next_action label correctly moves whenever I change the order. However, if I complete task 1, the label does not move to task 2.

**Comment by nikdoof** [comment]
This is another bug (issue #1) which is fixed in the current development branch

**Comment by iamtechman** [comment]
Thanks nidoof.  It works great now that I changed those lines.  The only thing is that I had to manually change them.  The latest commit did not include your changes.
