### ISSUE TITLE
Every item in Inbox has a next_action

### ISSUE THREAD

**Issue by RalphOnyx** [nikdoof/NextAction#7]
I'm new to programming and have used what I think is the latest revision by Timharton ("Behaviour with parallel taske now fixed as well." 224 lines of code).  Thank you very much for this.  The intended functionality works perfectly.

The issue I have is that every item in my Inbox also received a next_action label.  Please can someone advise me how to resolve this?  Thank you

**Comment by nikdoof** [comment]
@kajetanj has a [fork](https://github.com/kajetanj/NextAction/) that adds in a new option to disable inbox processing. I'll bring it into my version once I have time to do the next release.
